name: Formatting

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.x'
          channel: 'stable'
          cache: true
          
      - name: Check Flutter version
        run: flutter --version

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
